"""BedrockEmbedder: the port's contract, exercised with a fake boto3 client (deterministic,
free), plus one real-AWS smoke test gated on credential availability (skips loudly, same
convention as tests/embedders.py's OpenAI half).

Not added to tests/model/test_embedder_contract.py's ADAPTERS: that file's own header says
"do not edit this file to make it pass", and Titan v2 only serves 256/512/1024-wide vectors --
the shared NARROW_DIMENSIONS=64 fixture every parametrized body uses would need a per-adapter
translation that file was not written to carry. This file exercises the same invariants
(order preservation, declared width, blank-string refusal) at a width Titan actually supports.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from contracts import needs  # noqa: E402

pytestmark = needs("I")


class _FakeBody:
    def __init__(self, payload: dict) -> None:
        import json

        self._raw = json.dumps(payload).encode("utf-8")

    def read(self) -> bytes:
        return self._raw


class _FakeBedrockClient:
    """Deterministic: the vector is derived from the text so ordering is checkable."""

    def __init__(self, dimensions: int) -> None:
        self.dimensions = dimensions
        self.calls: list[dict] = []

    def invoke_model(self, *, modelId: str, body: str, contentType: str, accept: str) -> dict:
        import hashlib
        import json

        self.calls.append({"modelId": modelId, "body": json.loads(body)})
        text = json.loads(body)["inputText"]
        seed = int(hashlib.sha256(text.encode("utf-8")).hexdigest(), 16)
        vector = [((seed >> (i % 64)) % 1000) / 1000.0 for i in range(self.dimensions)]
        return {"body": _FakeBody({"embedding": vector, "inputTextTokenCount": len(text.split())})}


def test_model_and_dimensions_are_settled_without_a_probe() -> None:
    from governed_bi.model.bedrock_embedder import BedrockEmbedder

    embedder = BedrockEmbedder(client=_FakeBedrockClient(256), dimensions=256)
    assert embedder.model == "bedrock:amazon.titan-embed-text-v2:0"
    assert embedder.dimensions == 256


def test_only_256_512_1024_are_accepted() -> None:
    from governed_bi.model.bedrock_embedder import BedrockEmbedder

    with pytest.raises(ValueError, match="256/512/1024"):
        BedrockEmbedder(dimensions=64)


def test_batch_size_is_one_titan_has_no_batch_endpoint() -> None:
    from governed_bi.model.bedrock_embedder import BedrockEmbedder

    assert BedrockEmbedder.batch_size == 1


def test_embed_returns_one_vector_per_input_in_order() -> None:
    from governed_bi.model.bedrock_embedder import BedrockEmbedder

    client = _FakeBedrockClient(256)
    embedder = BedrockEmbedder(client=client, dimensions=256)
    texts = ["alpha", "bravo", "charlie"]
    vectors = embedder.embed(texts)
    assert len(vectors) == 3
    assert all(len(v) == 256 for v in vectors)
    # One request per text -- no batch endpoint (ports.py's documented Bedrock cost shape).
    assert len(client.calls) == 3
    assert [c["body"]["inputText"] for c in client.calls] == texts
    # Same text embeds to the same vector (deterministic fake), confirming order survived.
    assert embedder.embed(["alpha"])[0] == vectors[0]


def test_a_blank_string_is_refused_before_any_request() -> None:
    from governed_bi.model.bedrock_embedder import BedrockEmbedder

    client = _FakeBedrockClient(256)
    embedder = BedrockEmbedder(client=client, dimensions=256)
    with pytest.raises(ValueError, match="blank"):
        embedder.embed(["   "])
    assert client.calls == []


def test_a_provider_width_mismatch_raises() -> None:
    from governed_bi.model.bedrock_embedder import BedrockEmbedder

    class _WrongWidthClient(_FakeBedrockClient):
        def invoke_model(self, **kwargs: Any) -> dict:
            result = super().invoke_model(**kwargs)
            import json

            payload = json.loads(result["body"].read())
            payload["embedding"] = payload["embedding"][:-1]  # one short
            return {"body": _FakeBody(payload)}

    embedder = BedrockEmbedder(client=_WrongWidthClient(256), dimensions=256)
    with pytest.raises(ValueError, match="dimensions=256 but Titan returned"):
        embedder.embed(["alpha"])


def _aws_available() -> bool:
    import boto3

    try:
        boto3.client("sts").get_caller_identity()
        return True
    except Exception:  # noqa: BLE001
        return False


def test_a_real_bedrock_titan_call_returns_a_real_vector() -> None:
    if not _aws_available():
        pytest.skip(
            "no AWS credential resolvable via boto3's default chain. THIS CONTRACT DID NOT "
            "EXERCISE REAL BEDROCK on this run."
        )
    from governed_bi.model.bedrock_embedder import BedrockEmbedder

    embedder = BedrockEmbedder(dimensions=256)
    vectors = embedder.embed(["how many customers are there?"])
    assert len(vectors) == 1
    assert len(vectors[0]) == 256
    assert any(v != 0.0 for v in vectors[0])
